<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="13" passed="5" failed="2" skipped="6">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-02-13T18:16:03Z" name="automation suite" finished-at="2020-02-13T18:17:23Z" duration-ms="79535">
    <groups>
    </groups>
    <test started-at="2020-02-13T18:16:03Z" name="Login test" finished-at="2020-02-13T18:16:26Z" duration-ms="22294">
      <class name="com_TestCase.LoginPage_TestCase">
        <test-method is-config="true" signature="Setup()[pri:0, instance:com_TestCase.LoginPage_TestCase@78047b92]" started-at="2020-02-13T18:16:04Z" name="Setup" finished-at="2020-02-13T18:16:13Z" duration-ms="9706" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="loginPageTitleValidation()[pri:1, instance:com_TestCase.LoginPage_TestCase@78047b92]" started-at="2020-02-13T18:16:13Z" name="loginPageTitleValidation" finished-at="2020-02-13T18:16:18Z" duration-ms="4244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleValidation -->
        <test-method signature="LoginPageUIValidation()[pri:2, instance:com_TestCase.LoginPage_TestCase@78047b92]" started-at="2020-02-13T18:16:18Z" name="LoginPageUIValidation" finished-at="2020-02-13T18:16:18Z" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginPageUIValidation -->
        <test-method signature="LoginValidation()[pri:3, instance:com_TestCase.LoginPage_TestCase@78047b92]" started-at="2020-02-13T18:16:18Z" name="LoginValidation" finished-at="2020-02-13T18:16:25Z" duration-ms="7340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com_TestCase.LoginPage_TestCase@78047b92]" started-at="2020-02-13T18:16:25Z" name="tearDown" finished-at="2020-02-13T18:16:26Z" duration-ms="629" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com_TestCase.LoginPage_TestCase -->
    </test> <!-- Login test -->
    <test started-at="2020-02-13T18:16:26Z" name="Homepage Test" finished-at="2020-02-13T18:16:48Z" duration-ms="22430">
      <class name="com_TestCase.HomePage_TestCase">
        <test-method is-config="true" signature="Setup()[pri:0, instance:com_TestCase.HomePage_TestCase@2fd6b6c7]" started-at="2020-02-13T18:16:26Z" name="Setup" finished-at="2020-02-13T18:16:35Z" duration-ms="9195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="companiesButtonPresentValidation()[pri:1, instance:com_TestCase.HomePage_TestCase@2fd6b6c7]" started-at="2020-02-13T18:16:35Z" name="companiesButtonPresentValidation" finished-at="2020-02-13T18:16:47Z" duration-ms="12040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- companiesButtonPresentValidation -->
        <test-method signature="buttonsPresentValidation()[pri:2, instance:com_TestCase.HomePage_TestCase@2fd6b6c7]" started-at="2020-02-13T18:16:47Z" name="buttonsPresentValidation" finished-at="2020-02-13T18:16:47Z" duration-ms="279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buttonsPresentValidation -->
        <test-method signature="CombinedButtonClickValidation()[pri:3, instance:com_TestCase.HomePage_TestCase@2fd6b6c7]" started-at="2020-02-13T18:16:47Z" name="CombinedButtonClickValidation" finished-at="2020-02-13T18:16:48Z" duration-ms="82" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO0] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO0] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com_TestCase.HomePage_TestCase.CombinedButtonClickValidation(HomePage_TestCase.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CombinedButtonClickValidation -->
        <test-method signature="CombinedButtonClickValidation()[pri:3, instance:com_TestCase.HomePage_TestCase@2fd6b6c7]" started-at="2020-02-13T18:16:48Z" name="CombinedButtonClickValidation" finished-at="2020-02-13T18:16:48Z" duration-ms="67" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO0] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO0] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com_TestCase.HomePage_TestCase.CombinedButtonClickValidation(HomePage_TestCase.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CombinedButtonClickValidation -->
        <test-method signature="CombinedButtonClickValidation()[pri:3, instance:com_TestCase.HomePage_TestCase@2fd6b6c7]" started-at="2020-02-13T18:16:48Z" name="CombinedButtonClickValidation" finished-at="2020-02-13T18:16:48Z" duration-ms="64" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO0] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO0] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com_TestCase.HomePage_TestCase.CombinedButtonClickValidation(HomePage_TestCase.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CombinedButtonClickValidation -->
        <test-method signature="CombinedButtonClickValidation()[pri:3, instance:com_TestCase.HomePage_TestCase@2fd6b6c7]" started-at="2020-02-13T18:16:48Z" name="CombinedButtonClickValidation" finished-at="2020-02-13T18:16:48Z" duration-ms="61" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO0] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO0] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com_TestCase.HomePage_TestCase.CombinedButtonClickValidation(HomePage_TestCase.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CombinedButtonClickValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com_TestCase.HomePage_TestCase@2fd6b6c7]" started-at="2020-02-13T18:16:48Z" name="tearDown" finished-at="2020-02-13T18:16:48Z" duration-ms="623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com_TestCase.HomePage_TestCase -->
    </test> <!-- Homepage Test -->
    <test started-at="2020-02-13T18:16:48Z" name="Combined test" finished-at="2020-02-13T18:17:23Z" duration-ms="34528">
      <class name="com_TestCase.CombinedPage_TestCase">
        <test-method is-config="true" signature="Setup()[pri:0, instance:com_TestCase.CombinedPage_TestCase@3c72f59f]" started-at="2020-02-13T18:16:48Z" name="Setup" finished-at="2020-02-13T18:16:58Z" duration-ms="9170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="backButtonValidation()[pri:0, instance:com_TestCase.CombinedPage_TestCase@3c72f59f]" started-at="2020-02-13T18:16:58Z" name="backButtonValidation" finished-at="2020-02-13T18:17:09Z" duration-ms="11220" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO0] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO0] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com_TestCase.HomePage_TestCase.CombinedButtonClickValidation(HomePage_TestCase.java:46)
at com_TestCase.CombinedPage_TestCase.backButtonValidation(CombinedPage_TestCase.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- backButtonValidation -->
        <test-method signature="backButtonValidation()[pri:0, instance:com_TestCase.CombinedPage_TestCase@3c72f59f]" started-at="2020-02-13T18:17:09Z" name="backButtonValidation" finished-at="2020-02-13T18:17:13Z" duration-ms="4645" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO0] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO0] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com_TestCase.HomePage_TestCase.CombinedButtonClickValidation(HomePage_TestCase.java:46)
at com_TestCase.CombinedPage_TestCase.backButtonValidation(CombinedPage_TestCase.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- backButtonValidation -->
        <test-method signature="backButtonValidation()[pri:0, instance:com_TestCase.CombinedPage_TestCase@3c72f59f]" started-at="2020-02-13T18:17:13Z" name="backButtonValidation" finished-at="2020-02-13T18:17:18Z" duration-ms="4098" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO0] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO0] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com_TestCase.HomePage_TestCase.CombinedButtonClickValidation(HomePage_TestCase.java:46)
at com_TestCase.CombinedPage_TestCase.backButtonValidation(CombinedPage_TestCase.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- backButtonValidation -->
        <test-method signature="backButtonValidation()[pri:0, instance:com_TestCase.CombinedPage_TestCase@3c72f59f]" started-at="2020-02-13T18:17:18Z" name="backButtonValidation" finished-at="2020-02-13T18:17:22Z" duration-ms="4751" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO0] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO0] but found [CRMPRO]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com_TestCase.HomePage_TestCase.CombinedButtonClickValidation(HomePage_TestCase.java:46)
at com_TestCase.CombinedPage_TestCase.backButtonValidation(CombinedPage_TestCase.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- backButtonValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com_TestCase.CombinedPage_TestCase@3c72f59f]" started-at="2020-02-13T18:17:22Z" name="tearDown" finished-at="2020-02-13T18:17:23Z" duration-ms="635" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com_TestCase.CombinedPage_TestCase -->
    </test> <!-- Combined test -->
  </suite> <!-- automation suite -->
</testng-results>
